.\" Manpage for backup
.\" Contact 2021.rikio.dahlgren@uwcisak.jp to correct errors or typos
.TH man 6 "30 October 2019" "1.0" "backup man page"
.sh NAME
backup \- backup the database
.sh SYNOPSIS
bash backup.sh [location to be backed up to]
.sh DESCRIPTION
backup is a command that backs up the entirity of the RentalCarApp database to a location provided by the user.
.sh EXAMPLES
bash backup.sh /Volumes/johns_hard_drive_5GB
.sh AUTHOR
Rikio Dahlgren (2021.rikio.dahlgren@uwcisak.jp)
