.TH man 6 "28 October 2019" "1.0" "createCar man page"
.SH NAME
createCar \- create a new car
.sh SYNOPSIS
bash createCar.sh [license] [mode] [color] [passengers]
.sh DESCRIPTION
createCar is a command that creates a new record for a car in the database.
.sh EXAMPLES
bash createCar.sh LXH798 Mazda Red 3
.sh AUTHOR
Rikio Dahlgren (2021.rikio.dahlgren@uwcisak.jp)

.sh LXH798 Mazda Red 3
.sh AUTHOR
Rikio Dahlgren (2021.rikio.dahlgren@uwcisak.jp)


