.\" Manpage for create
.\" Contact 2021.rikio.dahlgren@uwcisak.jp to correct errors or typos.
.TH man 6 "28 October 2019" "1.0" "create man page"
.SH NAME
create \- create a new car
.sh SYNOPSIS
bash create.sh [license] [mode] [color] [passengers]
.sh DESCRIPTION 
create is a command that creates a new record for a car in the database. 
.sh EXAMPLES
bash create.sh LXH798 Mazda Red 3
.sh AUTHOR
Rikio Dahlgren (2021.rikio.dahlgren@uwcisak.jp)
 
