.\" Manpage for deleteCar 
.\" Contact 2021.rikio.dahlgren@uwcisak.jp to correct errors or typos
.TH man 6 "30 October 2019" "1.0" "deleteCar man page"
.SH NAME
deleteCar \- delete an existing car
.sh SYNOPSIS
bash deleteCar.sh [license plate] 
.sh DESCRIPTION
deleteCar is a command that deletes an existing car in the database
.sh EXAMPLES
bash deleteCar.sh [ABC123]
.sh AUTHOR
Rikio Dahlgren (2021.rikio.dahlgren@uwcisak.jp)
