.\" Manpage for editCar
.\" Contact 2021.rikio.dahlgren@uwcisak.jp to correct errors or typos
.TH man 6 "30 October 2019" "1.0" "editCar man page"
.sh NAME
editCar \- edit an existing car
.sh SYNOPSIS
bash editCar.sh [license plate] [model] [color] [passengers] 
.sh DESCRIPTION
editCar is a command that edits the information for a car in the database
.sh EXAMPLES
bash editCar.sh [ABC123] [Red] [Nissan] [4] 
.sh AUTHOR
Rikio Dahlgren (2021.rikio.dahlgren@uwcisak.jp)
