.\" Manpage for install
.\" Contact 2021.rikio.dahlgren@uwcisak.jp to correct errors or typos.
.TH man 6 "30 October 2019" "1.0" "install man page"
.SH NAME
install \- install the CarRentalApp on to the user's desktop
.sh SYNOPSIS
bash install.sh 
.sh DESCRIPTION
install is a command that creates a folder called CarRentalApp on the desktop. From there, it creates folders within called scripts, db, and tests. Within scripts, it copies in all of the necessary programs to run the program.
.sh EXAMPLES
bash install.sh
.sh AUTHOR
Rikio Dahlgren (2021.rikio.dahlgren@uwcisak.jp)
