.\" Manpage for recordTrip
.\" Contact 2021.rikio.dahlgren@uwcisak.jp to correct errors or typs
.TH man 6 "30 October 2019" "1.0" "recordTrip man page"
.SH NAME
recordTrip \- record a new trip
.sh SYNOPSIS
bash recordTrip.sh [distance] [start date] [finish date] [license plate]
.sh DESCRIPTION
recordTrip is a command that creates a new record for a trip in the database.
.sh EXAMPLES
bash recordTrip.sh 50 10/21/2019 11/1/2019 ABC123
.sh AUTHOR
Rikio Dahlgren (2021.rikio.dahlgren@uwcisak.jp)
